name: Publish Docker Image on Release

on:
  release:
    types: [published]

env:
  ARCHITECTURES: linux/amd64
  IMAGE_NAME: rehlds-cstrike
  IMAGE_NAMESPACE: dimankiev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup repository
      uses: actions/checkout@v3.1.0

    - name: Set up QEMU for multi-arch builds with buildx
      uses: docker/setup-qemu-action@v2
      with:
        platforms: ${{ env.ARCHITECTURES }}

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to ghcr
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: metadata
      uses: docker/metadata-action@v5.5.1
      with:
        images: |
          ghcr.io/${{ env.IMAGE_NAMESPACE }}/${{ env.IMAGE_NAME }}
        tags: |
          type=semver,pattern={{major}}.{{minor}},enable=true
          type=semver,pattern=latest,enable=true
          type=edge,branch=master
    
    - name: Build and push Docker image to GitHub
      uses: docker/build-push-action@v5.1.0
      with:
        context: .
        platforms: ${{ env.ARCHITECTURES }}
        push: true
        file: Dockerfile
        provenance: false
        tags: ${{ steps.metadata.outputs.tags }}
        labels: ${{ steps.metadata.outputs.labels }}
    
    - name: Log in to Docker Hub
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
      with:
        images: ${{ env.IMAGE_NAMESPACE }}/${{ env.IMAGE_NAME }}

    - name: Build and push Docker image
      id: push
      uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: Generate artifact attestation
      uses: actions/attest-build-provenance@v2
      with:
        subject-name: index.docker.io/my-docker-hub-namespace/my-docker-hub-repository
        subject-digest: ${{ steps.push.outputs.digest }}
        push-to-registry: true
