name: Publish Docker Image

on:
  push:
    branches:
      - "master"
    tags:
      - "*.*"

env:
  ARCHITECTURES: linux/amd64
  IMAGE_NAME: rehlds-cstrike
  IMAGE_NAMESPACE: blsalin

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup repository
      uses: actions/checkout@v3.1.0

    - name: Set up QEMU for multi-arch builds with buildx
      uses: docker/setup-qemu-action@v2
      with:
        platforms: ${{ env.ARCHITECTURES }}

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to ghcr
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: metadata
      uses: docker/metadata-action@v5.5.1
      with:
        images: |
          ghcr.io/${{ env.IMAGE_NAMESPACE }}/${{ env.IMAGE_NAME }}
        tags: |
          type=semver,pattern={{major}}.{{minor}},enable=true
          type=semver,pattern=latest,enable=true
          type=edge,branch=master
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v5.1.0
      with:
        context: .
        platforms: ${{ env.ARCHITECTURES }}
        push: true
        file: Dockerfile
        provenance: false
        tags: ${{ steps.metadata.outputs.tags }}
        labels: ${{ steps.metadata.output.labels }}
